print("what is the name of the gift giver?")
name=raw_input()
print("What is the present they gave you")
present=raw_input()
print("how old were you on your birthday?")
age=int(raw_input())
print("what is your name")
yourName=raw_input()
print("Dear "+name + ", ")
print("")
print("thank you for the "+present +". ")
print("i really like it. I cant belive")
print("i am already "+str(age) + "years old,but")
print("it does not feel much different than being ")
print(str(age-1)+".")
print("")
print("sincerely.")
print("")
print(yourName)
